# # # # # # # # # #
#
# Store API
# Test Application API's
# Doom Emacs Rest Client Configuration File
#
# Global Environment Variables
:base_url=http://localhost:5000/api/v1
#
# # # # # # # # # #
# === AUTHORIZATION API ===
#
# === GET ===
#
GET :base_url/login
Host: :base_url
Content-Type: application/json
Accept: application/json
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJqb2huIiwiaWF0IjoxNzM1ODk2MjExLCJleHAiOjE3Mzg0ODgyMTF9.nrRgWzF99XQZz_lImRt7VUwNMJ9vnQQpf8a64wMDz8U
#
# === POST ====
# 
POST :base_url/register
Content-Type: application/json
Accept: application/json
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
{
    "name": "john",
    "email": "john@gmail.com",
    "password": "password"
}
#
# # # # # # # # # #
