# Test Application API's
# Doom Emacs Rest Client Configuration File
#
# Global Environment Variables
:base_url=http://localhost:3000/api/v1/tasks

=== GET ====
# All Tasks
GET :base_url
Accept: application/json
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

# Task By Identity
GET :base_url/1
Accept: application/json
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

=== POST ===
# Create Task
POST :base_url
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
{
    "id": "3",
    "name": "Third Task"
}

=== PATCH ===
# Update Task
PATCH :base_url/1
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
{
    "name": "New Task Name"
}

=== DELETE ===
# Delete Task
DELETE :base_url/1
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
