app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5436/syscomz
      pool-size: 30
      username: postgres
      password: 'postgres'

server:
  error:
    include-binding-errors: always
    include-message: always